#!/bin/bash

# Internet Indicator
# by Lutfa Ilham (Modified)

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

SERVICE_NAME="Internet Indicator"

function loop() {
  while true; do
    ledon -lan dis
    if ping -c 1 -W 2 8.8.8.8 > /dev/null 2>&1; then
      ledon -lan on
    else
      ledon -lan off
    fi
    sleep 1
  done
}

function start() {
  echo -e "Starting ${SERVICE_NAME} service ..."
  screen -AmdS internet-indicator "${0}" -l
}

function stop() {
  echo -e "Stopping ${SERVICE_NAME} service ..."
  PID=$(screen -list | grep internet-indicator | awk -F '[.]' '{print $1}' | xargs)
  if [ -n "$PID" ]; then
    kill $PID
  fi
}

function usage() {
  cat <<EOF
Usage:
  -r  Run ${SERVICE_NAME} service
  -s  Stop ${SERVICE_NAME} service
EOF
}

case "${1}" in
  -l)
    loop
    ;;
  -r)
    start
    ;;
  -s)
    stop
    ;;
  *)
    usage
    ;;
esac

