#!/bin/bash

# Internet Indicator Trigger
# Powered by Frdmx-Wrt Community

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

SERVICE_NAME="Internet Indicator"
DETECTOR_SCRIPT="/usr/sbin/ledon"

function loop() {
  while true; do

    if curl -X "HEAD" --connect-timeout 3 -so /dev/null "http://bing.com"; then

      $DETECTOR_SCRIPT -lan dis
      $DETECTOR_SCRIPT -power dis
      
      sleep 0.5
      
      $DETECTOR_SCRIPT -lan on
      $DETECTOR_SCRIPT -power on
    else

      $DETECTOR_SCRIPT -lan off
      $DETECTOR_SCRIPT -power off
    fi

    sleep 1
  done
}

function start() {
  echo -e "Starting ${SERVICE_NAME} service ..."
  screen -AmdS internet-indicator "$(readlink -f "$0")" -l
}

function stop() {
  echo -e "Stopping ${SERVICE_NAME} service ..."
  PID=$(screen -list | grep internet-indicator | awk -F '[.]' '{print $1}' | xargs)
  if [ ! -z "$PID" ]; then
    kill $PID
  fi
}

function usage() {
  cat <<EOF
Usage:
  $0 -r  Run ${SERVICE_NAME} service
  $0 -s  Stop ${SERVICE_NAME} service
EOF
}

case "${1}" in
  -l)
    loop
    ;;
  -r)
    start
    ;;
  -s)
    stop
    ;;
  *)
    usage
    ;;
esac
