#!/bin/sh
. /usr/share/libubox/jshn.sh

case "$1" in
    list)
        echo '{ "get_temp": {}, "get_cpu": {}, "get_traffic": {} }'
    ;;
    call)
        case "$2" in
            get_temp)
                if [ -f /sys/class/thermal/thermal_zone0/temp ]; then
                    RAW=$(cat /sys/class/thermal/thermal_zone0/temp)
                    json_init
                    json_add_int "raw" "$RAW"
                    json_dump
                fi
            ;;
            get_cpu)
                if [ -f /proc/stat ]; then
                    CPU_INFO=$(grep '^cpu ' /proc/stat)
                    json_init
                    json_add_string "stat" "$CPU_INFO"
                    json_dump
                fi
            ;;
            get_traffic)
                if [ -f /proc/net/dev ]; then
                    NET_DATA=$(awk 'NR>2 {if($1 != "lo:") print $1, $2, $10}' /proc/net/dev | sort -rnk2 | head -n1 | sed 's/://')
                    RX=$(echo "$NET_DATA" | awk '{print $2}')
                    TX=$(echo "$NET_DATA" | awk '{print $3}')
                    json_init
                    json_add_int "rx" "${RX:-0}"
                    json_add_int "tx" "${TX:-0}"
                    json_dump
                fi
            ;;
        esac
    ;;
esac
