#!/bin/sh

# 1. Password root & Izin File
(echo "root"; sleep 1; echo "root") | passwd > /dev/null
[ -f "/usr/sbin/free.sh" ] && chmod 0755 /usr/sbin/free.sh
[ -f "/etc/rc.local" ] && chmod +x /etc/rc.local

# 2. Konfigurasi UCI (1-Port LAN + WAN via Modem/USB)
uci batch <<EOF
    # System & Timezone
    set system.@system[0].hostname='FRDM-X'
    set system.@system[0].timezone='WIB-7'
    set system.@system[0].zonename='Asia/Jakarta'
    del system.ntp.server
    add_list system.ntp.server='0.id.pool.ntp.org'
    add_list system.ntp.server='1.id.pool.ntp.org'
    
    # Set Port Tunggal (eth0) sebagai LAN
    delete network.lan
    set network.lan=interface
    set network.lan.proto='static'
    set network.lan.device='eth0'
    set network.lan.ipaddr='192.168.1.1'
    set network.lan.netmask='255.255.255.0'
    
    # Internet dari Modem USB (mm)
    set network.mm=interface
    set network.mm.proto='modemmanager'
    set network.mm.device='auto'
    set network.mm.apn='internet'
    set network.mm.peerdns='1'
    set network.mm.metric='10'
    
    # Internet dari Tethering HP (usb0)
    set network.tethering=interface
    set network.tethering.proto='dhcp'
    set network.tethering.device='usb0'
    set network.tethering.metric='20'
    
    # Bersihkan interface yang tidak ada fisiknya (eth1)
    delete network.wan
    delete network.wan6
    
    # Firewall: Gabungkan Modem & USB ke zona WAN
    del_list firewall.wan.network='wan'
    del_list firewall.wan.network='wan6'
    add_list firewall.wan.network='mm'
    add_list firewall.wan.network='tethering'
    
    commit network
    commit system
    commit firewall
    commit dhcp
EOF

# 3. Konfigurasi WiFi Otomatis (Jika ada kartu WiFi internal)
if [ -e /etc/config/wireless ]; then
    # Hapus config lama dan deteksi ulang hardware
    rm -f /etc/config/wireless
    wifi detect > /etc/config/wireless
    
    # Aktifkan semua radio WiFi yang ditemukan (radio0, radio1, dst)
    i=0
    while uci get wireless.radio$i >/dev/null 2>&1; do
        uci set wireless.radio$i.disabled='0'
        # Buat Access Point (SSID)
        uci set wireless.default_radio$i=wifi-iface
        uci set wireless.default_radio$i.device="radio$i"
        uci set wireless.default_radio$i.network='lan'
        uci set wireless.default_radio$i.mode='ap'
        uci set wireless.default_radio$i.ssid="FRDM-X_WiFi_$i"
        uci set wireless.default_radio$i.encryption='psk2'
        uci set wireless.default_radio$i.key='12345678'
        i=$((i+1))
    done
    uci commit wireless
fi

# 4. Optimasi & Background Service
sed -i 's/^option check_signature/# option check_signature/g' /etc/opkg.conf
for dev in /sys/bus/usb/devices/*/power/control; do [ -e "$dev" ] && echo "on" > "$dev" 2>/dev/null; done

(
    /etc/init.d/network restart
    sleep 5
    wifi up
    /etc/init.d/modemmanager restart
    [ -f "/usr/sbin/free.sh" ] && /usr/sbin/free.sh
) &

# 5. Ttyd & Bash Fix
if [ -f /bin/bash ]; then
    uci set ttyd.@ttyd[0].command='/bin/bash --login'
    uci commit ttyd
    /etc/init.d/ttyd enable
    /etc/init.d/ttyd restart
fi

exit 0
