#!/bin/sh

echo "Clearing root password..."
passwd -d root > /dev/null 2>&1

echo "Setting file permissions..."
for file in \
    /usr/bin/huawei.py \
    /usr/libexec/rpcd/luci-temp \
    /usr/bin/frdmx-andro \
    /usr/sbin/led \
    /usr/sbin/ledon \
    /bin/frdmx_net \
    /sbin/free.sh \
    /sbin/yess \
    /etc/rc.local \
    /etc/custom_service/start_service.sh \
    /etc/init.d/todong \
    /www/vnstati/vnstati.sh \
    /www/cgi-bin/traffic \
    /etc/hotplug.d/usb/90-frdmx-modem \
    /etc/hotplug.d/iface/99-frdmx-watchdog; do
    [ -f "$file" ] && chmod +x "$file"
done

echo "Configuring UCI settings via batch..."
uci batch <<EOF
set system.@system[0].hostname='FRDMX'
set system.@system[0].timezone='WIB-7'
set system.@system[0].zonename='Asia/Jakarta'

delete system.ntp.server
add_list system.ntp.server='0.id.pool.ntp.org'
add_list system.ntp.server='1.id.pool.ntp.org'
add_list system.ntp.server='ntp.bmkg.go.id'
add_list system.ntp.server='time.google.com'

delete network.lan
set network.lan=interface
set network.lan.device='eth0'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'
set network.lan.delegate='0'

set network.tethering=interface
set network.tethering.proto='dhcp'
set network.tethering.device='usb0'
set network.tethering.metric='10'

set network.modem=interface
set network.modem.proto='modemmanager'
set network.modem.device='wwan0'
set network.modem.apn='internet'
set network.modem.auth='none'
set network.modem.metric='20'

delete network.wan6
set network.globals=globals
set network.globals.ula_prefix=''

delete firewall.@zone[1].network
add_list firewall.@zone[1].network='tethering'
add_list firewall.@zone[1].network='modem'

delete dhcp.lan
set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
set dhcp.lan.ra='disabled'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ndp='disabled'

commit system
commit network
commit firewall
commit dhcp
EOF

echo "Applying system optimizations..."
sed -i 's/^option check_signature/# option check_signature/g' /etc/opkg.conf 2>/dev/null

# Set BFQ I/O untuk Storage Internal eMMC
if [ -d /sys/block/mmcblk0 ]; then
    echo bfq > /sys/block/mmcblk0/queue/scheduler 2>/dev/null
fi

for dev in /sys/bus/usb/devices/*/power/control; do 
    [ -e "$dev" ] && echo "on" > "$dev" 2>/dev/null
done

[ -f /etc/php.ini ] && sed -i 's/^memory_limit.*/memory_limit = 64M/' /etc/php.ini

# me909s and dw5821e
echo "Removing USB modeswitch entries..."
sed -i -e '/12d1:15c1/,+5d' -e '/413c:81d7/,+5d' /etc/usb-mode.json

# xmm-modem
echo "Disabling XMM-Modem..."
uci set xmm-modem.@xmm-modem[0].enable='0' 2>/dev/null || uci set xmm-modem.@xmm-modem.enable='0' 2>/dev/null
uci commit xmm-modem

echo "Creating application symlinks for TinyFM..."
mkdir -p /www/tinyfm
ln -sf / /www/tinyfm/rootfs
ln -sf /etc/openclash/ /www/tinyfm/openclash 2>/dev/null
ln -sf /etc/nikki/ /www/tinyfm/nikki 2>/dev/null

echo "Registering scripts to Startup (rc.local)..."
sed -i '/start_service.sh/d' /etc/rc.local 2>/dev/null
sed -i '/\/sbin\/yess/d' /etc/rc.local 2>/dev/null

if [ -f "/sbin/yess" ]; then
    sed -i '/exit 0/i /sbin/yess &' /etc/rc.local
fi

if [ -f "/etc/custom_service/start_service.sh" ]; then
    sed -i '/exit 0/i (sleep 30 && /bin/sh /etc/custom_service/start_service.sh) &' /etc/rc.local
fi

echo "Applying permissions and sysctl..."
chmod 600 /etc/crontabs/root 2>/dev/null
sysctl -p /etc/sysctl.conf >/dev/null 2>&1

[ -f "/sbin/free.sh" ] && sh /sbin/free.sh >/dev/null 2>&1

echo "Cleaning up, completed setup..."
exit 0
