#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance "modem_lock"  
    procd_set_param command /usr/bin/modem-lock   
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 modem-lock 2>/dev/null
}
