#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1
PROG=/usr/bin/wwan-hotplug.sh

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall -9 wwan-hotplug.sh >/dev/null 2>&1
}

service_status() {
    if pgrep -f "$PROG" > /dev/null; then
        echo "WWAN hotplug service is running."
    else
        echo "WWAN hotplug service is not running."
    fi
}
