#!/bin/sh

echo "Clearing root password..."
passwd -d root > /dev/null 2>&1

echo "Setting file permissions..."
for file in \
    /usr/bin/7z \
    /usr/bin/cpustat \
    /usr/bin/huawei.py \
    /usr/libexec/rpcd/luci-temp \
    /usr/bin/netspeedtest.sh \
    /usr/bin/ookla-speedtest \
    /usr/bin/speedtest \
    /bin/getcpu \
    /sbin/free.sh \
    /etc/rc.local \
    /etc/custom_service/start_service.sh \
    /etc/init.d/todong \
    /www/vnstati/vnstati.sh \
    /www/cgi-bin/traffic \
    /etc/hotplug.d/net/25-modemmanager-net; do
    [ -f "$file" ] && chmod +x "$file"
done


echo "[*] Mengonfigurasi pengaturan UCI"
uci batch <<EOF
set system.@system.hostname='OpenWrt'
set system.@system.timezone='WIB-7'
set system.@system.zonename='Asia/Jakarta'
delete system.ntp.server
add_list system.ntp.server='0.id.pool.ntp.org'
add_list system.ntp.server='1.id.pool.ntp.org'
add_list system.ntp.server='ntp.bmkg.go.id'
add_list system.ntp.server='time.google.com'
EOF

# JARINGAN
uci delete network.lan 2>/dev/null
uci delete network.br_lan 2>/dev/null
uci delete network.br-lan 2>/dev/null

# 1. Konfigurasi Device
uci set network.@device=device
uci set network.@device.name='br-lan'
uci set network.@device.type='bridge'
uci add_list network.@device.ports='eth0'
uci set network.@device.ipv6='0'
uci set network.@device.mtu='1500'

# 2. Konfigurasi Interface LAN
uci set network.lan=interface
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='0'
uci set network.lan.multipath='off'

# 4. Konfigurasi Interface
uci delete network.wan 2>/dev/null
uci set network.wan=interface
uci set network.wan.proto='dhcp'
uci set network.wan.device='eth1'
uci set network.wan.metric='5'

uci delete network.tethering 2>/dev/null
uci set network.tethering=interface
uci set network.tethering.proto='dhcp'
uci set network.tethering.device='usb0'
uci set network.tethering.metric='10'

uci delete network.wan6 2>/dev/null

# BATCH LANJUTAN
uci batch <<EOF
delete dhcp.lan
set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
set dhcp.@dnsmasq.dnsforwardmax='1500'
set dhcp.@dnsmasq.cachesize='5000'
set dhcp.@dnsmasq.min_ttl='300'
delete uhttpd.main.listen_http
delete uhttpd.main.listen_https
add_list uhttpd.main.listen_http='0.0.0.0:80'
add_list uhttpd.main.listen_http='[::]:80'
add_list uhttpd.main.listen_https='0.0.0.0:443'
add_list uhttpd.main.listen_https='[::]:443'
set uhttpd.main.redirect_https='0'
set uhttpd.main.home='/www'
set uhttpd.main.rfc1918_filter='1'
set uhttpd.main.max_requests='50'
set uhttpd.main.max_connections='100'
set uhttpd.main.cgi_prefix='/cgi-bin'
delete uhttpd.main.interpreter
add_list uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
set uhttpd.main.index_page='index.html, index.php'
set uhttpd.main.script_timeout='3600'
set uhttpd.main.network_timeout='30'
set uhttpd.main.http_keepalive='20'
set uhttpd.main.tcp_keepalive='1'
set uhttpd.main.ubus_prefix='/ubus'
commit system
commit network
commit dhcp
commit uhttpd
EOF

# AUTOMASI DAN OPTIMALISASI STORAGE
echo "[*] Mengonfigurasi otomatisasi block-mount (fstab)"
uci batch <<EOF
set fstab.global=global
set fstab.global.anon_swap='0'
set fstab.global.anon_mount='1'
set fstab.global.auto_swap='1'
set fstab.global.auto_mount='1'
set fstab.global.check_fs='0'
commit fstab
EOF

if [ -f /etc/init.d/fstab ]; then
    /etc/init.d/fstab enable >/dev/null 2>&1
fi

(
    sleep 15
    if [ -x /sbin/block ]; then
        /sbin/block mount
    fi
) &

if [ -f /etc/config/hd-idle ]; then
    echo "[*] Mengaktifkan otomatisasi standby HDD (hd-idle)"
    uci batch <<EOF
set hd-idle.@hd-idle=hd-idle
set hd-idle.@hd-idle.enabled='1'
set hd-idle.@hd-idle.idle_time='10'
set hd-idle.@hd-idle.unit='minutes'
commit hd-idle
EOF
    /etc/init.d/hd-idle enable >/dev/null 2>&1
fi

echo "[*] Menyinkronkan zona Firewall"
i=0
while true; do
    zone_name=$(uci -q get firewall.@zone[$i].name)
    if [ -z "$zone_name" ]; then
        break
    fi
    if [ "$zone_name" = "wan" ]; then
        uci -q delete firewall.@zone[$i].network
        uci add_list firewall.@zone[$i].network='wan'
        uci add_list firewall.@zone[$i].network='tethering'
        uci commit firewall
        break
    fi
    i=$((i+1))
done

echo "[*] Menerapkan optimalisasi sistem firmware"
if [ -f /etc/opkg.conf ]; then
    sed -i 's/^option check_signature/# option check_signature/g' /etc/opkg.conf 2>/dev/null
fi

if [ -d /sys/block/mmcblk0 ]; then echo bfq > /sys/block/mmcblk0/queue/scheduler 2>/dev/null; fi
if [ -d /sys/block/sda ]; then echo bfq > /sys/block/sda/queue/scheduler 2>/dev/null; fi
if [ -d /sys/block/nvme0n1 ]; then echo bfq > /sys/block/nvme0n1/queue/scheduler 2>/dev/null; fi

for dev in /sys/bus/usb/devices/*/power/control; do 
    if [ -f "$dev" ]; then
        echo "on" > "$dev" 2>/dev/null
    fi
done

if [ -f /etc/php.ini ]; then
    sed -i 's/^memory_limit.*/memory_limit = 64M/' /etc/php.ini 2>/dev/null
fi

if [ -f /etc/usb-mode.json ]; then
    sed -i -e '/12d1:15c1/,+5d' -e '/413c:81d7/,+5d' /etc/usb-mode.json 2>/dev/null
fi

if uci -q get xmm-modem.@xmm-modem >/dev/null; then
    uci set xmm-modem.@xmm-modem.enable='0'
    uci commit xmm-modem
fi

echo "Creating application symlinks for TinyFM (Direct Execution)..."
mkdir -p /www/tinyfm
mkdir -p /etc/openclash /etc/nikki
rm -rf /www/tinyfm/rootfs /www/tinyfm/openclash /www/tinyfm/nikki
ln -sf / /www/tinyfm/rootfs
ln -sf /etc/openclash /www/tinyfm/openclash
ln -sf /etc/nikki /www/tinyfm/nikki

# PROFILE
echo "[*] Menghapus sysinfo bawaan dan mengonfigurasi profil terminal..."

rm -f /etc/profile.d/30-sysinfo.sh

if [ -f /usr/lib/xral ]; then
    chmod 755 /usr/lib/xral
fi

if [ -f /etc/profile ]; then
    sed -i '/\/usr\/lib\/xral/d' /etc/profile 2>/dev/null
    sed -i '/30-sysinfo.sh/d' /etc/profile 2>/dev/null
    
    echo "" >> /etc/profile
    echo "# Jalankan sysinfo frdmx" >> /etc/profile
    echo "[ -x /usr/lib/xral ] && /bin/sh /usr/lib/xral" >> /etc/profile
fi

history -c 2>/dev/null
rm -f ~/.ash_history 2>/dev/null

echo "[*] Menerapkan banner komunitas kustom..."
cat << 'EOF' > /etc/banner
  ___                __        __    _   
 / _ \ _ __   ___ _ _\ \      / / __| |_ 
| | | | '_ \ / _ \ '_ \ \ /\ / / '__| __|
| |_| | |_) |  __/ | | \ V  V /| |  | |_ 
 \___/| .__/ \___|_| |_|\_/\_/ |_|   \__|
      |_| F R E E D O M - I N T E R N E T

EOF

echo "Banner kustom sukses terpasang!"

echo "[*] Mendaftarkan skrip otomatis ke Startup (rc.local)..."
if [ -f /etc/rc.local ]; then
    sed -i '/_service.sh/d' /etc/rc.local 2>/dev/null
    sed -i '/\/sbin\/yess/d' /etc/rc.local 2>/dev/null

    if [ -f "/etc/custom_service/start_service.sh" ]; then
        sed -i '/exit 0/i (sleep 30 && /bin/sh /etc/custom_service/start_service.sh) &' /etc/rc.local
    fi

    if [ -f "/sbin/yess" ]; then
        sed -i '/exit 0/i /sbin/yess &' /etc/rc.local
    fi
else
    echo "[!] Peringatan: /etc/rc.local tidak ditemukan."
fi

echo "[*] Menerapkan perizinan crontabs dan eksekusi Sysctl Repo..."
if [ -f /etc/crontabs/root ]; then
    chmod 600 /etc/crontabs/root 2>/dev/null
fi

if [ -f /etc/sysctl.conf ]; then
    sysctl -p /etc/sysctl.conf >/dev/null 2>&1
fi

if [ -f "/sbin/free.sh" ]; then
    sh /sbin/free.sh >/dev/null 2>&1
fi

echo "   Selesai!         "
exit 0
