#!/bin/sh
# Network Watchdog using httping - frdmx-Wrt Community

if [ "$ACTION" = "ifup" ]; then
    . /lib/functions.sh
    . /lib/functions/network.sh

    IS_WAN_ZONE=$(ubus call network.interface dump | jsonfilter -e "@.interface[@.interface=\"$INTERFACE\"].data.zone")
    
    if [ "$IS_WAN_ZONE" = "wan" ]; then
        sleep 8
        
        if ! httping -c 2 -t 4 -g http://google.com >/dev/null 2>&1; then
            echo "[Watchdog] Koneksi HTTP macet pada $INTERFACE. Mulai ulang jaringan..." > /dev/kmsg
            
            ubus call network.interface.$INTERFACE down
            sleep 3
            ubus call network.interface.$INTERFACE up
        else
            echo "[Watchdog] Koneksi internet pada $INTERFACE sukses terverifikasi via HTTP." > /dev/kmsg
        fi
    fi
fi
