#!/bin/bash
# Smart Hybrid Optimization Script for Community FW (Universal Version)
# Works perfectly on x86_64, Amlogic (S905X)

for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do 
    echo "schedutil" > "$i" 2>/dev/null
done

# Optimasi Batching Jaringan tingkat Kernel agar CPU lebih hemat daya
echo "16" > /proc/sys/net/core/gro_normal_batch 2>/dev/null

ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
    CPUS=$(nproc)
    RPS_MASK=$(printf '%x' $(( (1 << CPUS) - 1 )))
    
    for dev in /sys/class/net/*; do
        IFACE=$(basename "$dev")
        [ "$IFACE" = "lo" ] && continue
        for rps in /sys/class/net/"$IFACE"/queues/rx-*/rps_cpus; do echo "$RPS_MASK" > "$rps" 2>/dev/null; done
        for xps in /sys/class/net/"$IFACE"/queues/tx-*/xps_cpus; do echo "$RPS_MASK" > "$xps" 2>/dev/null; done
    done

else
    IRQ_ETH=$(awk -F: '/eth0/ {print $1}' /proc/interrupts | sed 's/ //g' | head -n 1)
    [ ! -z "$IRQ_ETH" ] && echo "e" > /proc/irq/$IRQ_ETH/smp_affinity 2>/dev/null
    
    for irq in $(awk -F: '/dwc3|usb|ehci/ {print $1}' /proc/interrupts | sed 's/ //g'); do 
        echo "d" > /proc/irq/$irq/smp_affinity 2>/dev/null
    done
fi

for usb in /sys/bus/usb/devices/*/power/control; do 
    echo "on" > "$usb" 2>/dev/null
done

for usb in /sys/bus/usb/devices/*/power/autosuspend; do 
    echo "-1" > "$usb" 2>/dev/null
done
