# =====================================================================================
# Build OpenWrt 25.12.1 Amlogic - Final Edition (Maret 2026)
# =====================================================================================

name: Amlogic FRDMX

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "openwrt:25.12.2"
        type: choice
        options:
          - openwrt:25.12.2
          - openwrt:24.10.6
          - immortalwrt:25.12.1
      openwrt_board:
        description: "Select device board"
        required: false
        default: "s905x-b860h"
        type: choice
        options:
          - s905
          - s905x
          - s905x-b860h
          - s905x2-hg680fj
          - s905x3
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.18.y"
        type: choice
        options:
          - 6.6.y
          - 6.12.y
          - 6.18.y
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "atho13/kernel"
        type: choice
        options:
          - ophub/kernel
          - atho13/kernel
      kernel_usage:
        description: "Set the tags of the stable kernel."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
      openwrt_ip:
        description: "Set OpenWrt default IP address."
        required: false
        default: "192.168.1.1"

env:
  TZ: Asia/Jakarta
  IMAGEBUILDER_SH: config/imagebuilder/frdmx.sh

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E apt-get -y install zstd fakeroot
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        run: |
          sudo mkdir -p /builder
          sudo truncate -s 20G /builder/mnt.img
          sudo losetup /dev/loop6 /builder/mnt.img
          sudo mkfs.xfs /dev/loop6
          sudo mount /dev/loop6 /builder
          sudo chown -R runner:runner /builder
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Build OpenWrt Rootfs
        id: imagebuilder
        run: |
          chmod +x ${IMAGEBUILDER_SH}
          ./${IMAGEBUILDER_SH} ${{ github.event.inputs.releases_branch }}
          echo "build_tag=OpenWrt_$(date +%Y%m%d_%H%M)" >> $GITHUB_ENV
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Packaging Amlogic (.img)
        id: packaging
        if: steps.imagebuilder.outputs.status == 'success'
        uses: atho13/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: output/*rootfs.tar.*
          openwrt_ip: ${{ github.event.inputs.openwrt_ip }}
          openwrt_board: ${{ github.event.inputs.openwrt_board }}
          openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
          kernel_repo: ${{ github.event.inputs.kernel_repo }}
          kernel_usage: ${{ github.event.inputs.kernel_usage }}
          auto_kernel: ${{ github.event.inputs.auto_kernel }}

      - name: Move Repack Result to Output
        if: steps.packaging.outcome == 'success'
        run: |
          sudo cp -v ${{ env.PACKAGED_OUTPUTPATH }}/*.img* output/ 2>/dev/null || true
          echo "Final check folder output:"
          ls -lh output/
          
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.build_tag }}
          artifacts: "output/*"
          allowUpdates: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## OpenWrt For Amlogic Only
            - **Board**: ${{ github.event.inputs.openwrt_board }}
            - **Kernel**: ${{ github.event.inputs.openwrt_kernel }} (${{ github.event.inputs.kernel_repo }})
            - **IP**: ${{ github.event.inputs.openwrt_ip }}
